### ISSUE TITLE
breadcrumb is not displayed correctly for long path

### ISSUE THREAD

**Issue by PavelD** [jmjuanes/siimple#84]
**Describe the bug**
On small displays long path is not correct. The backgoroud element stick on 1st line and text overflow to the other elements.

**To Reproduce**
* create `breadcrumb` object with many links inside
*create `siimple-box--primary` right after for better demonstration
* Try to read and navigate to the links in the end of the list

**Expected behavior**
* links are readable
* The `siimple-breadcrumb` div element will be extended to more lines.

**Screenshots or Project link**
* The number of the links in demo has been extended to demonstrate the issue on big screens as well as on the small mobile.
* Live demo of the issue: https://liveweave.com/gWtzFJ

**Desktop (please complete the following information):**
* OS:  windows 7
* Browser: Firefox
* Version: 78.5.0esr

**Smartphone (please complete the following information):**
* Device: some low cost Vodafone
* OS: android
* Browser: chrome
* Version: 87

**Comment by jmjuanes** [comment]
Hi! This seems that has been fixed in `v4`. There is a [demo](https://siimple.xyz/playground#html=DwEwlgbgBAxgNgQwM5ILwCIAWyC0AHHAFnQD4AoKSqUSWRFDGAJwFcBbAIySmyRw4DmOOGAGYALlDB8mAexYA7EAFMQpClU01o8ZGnTN2HUgEYkkuMojK4UOLIUCoeBAOVQFCNsuAB6cBDkmloBdHqMrJykAExKdlY2dg5OLm4eXj7%2BkEHBlNphDAaRxiQAzEwg8da29o7Oru6e3n4BObn5uoWGUSSE4phVibUpDenNWYEa7aGd%2Bt0lAKz9gzXJ9WlNma1TwR30c8WkSwOW1Ul1qY0ZLdk7N5P35GRAA&config=JYWwDg9gTgLgBAIwIYGcCmcBmUIjgIgAEVhQwAbNAejCjXRgFpl18BuAKDQA9JY4AJmkxIAruXgBvDnFlwQEAePoAuOJIC%2BAGhlzR6AELQhUI9zUwootDrlx9aAEoQIMAMowAnpRQWrN3VkAOhCWAI1OIA%3D%3D).
